### ISSUE TITLE
Is this really necessary?

### ISSUE THREAD

**Issue by jbreckmckye** [fanmingfei/array-reverse-ios12#16]
I assume this issue will be solved soon: a fix is already committed and the issue is major enough to justify a software update by Apple. One expects that very few users will remain stuck on iOS 12.0.

That being the case, is there really a need for this library?

I am concerned that if this gets into a common NPM dependency, it might be quite hard to shift: all it takes is one library to fail to remove it and we will all end up with runtime bloat in our JavaScript applications until the end of time.

**Comment by fanmingfei** [comment]
No matter how it upgrade, there will always be users in this version.  A business company, They have to consider this part of the user, helpless...

**Comment by jbreckmckye** [comment]
No. We cannot polyfill for every regression present in any release of any browser. That way lies madness. What you will end up doing is lugging around a whole polyfill JavaScript runtime 'just in case' a user is stuck on an obscure version of an obscure browser, a browser that will very likely be broken for many sites anyway.

Worse, by patching over user agent bugs you remove an incentive for users to upgrade from outdated and insecure browsers. All web technologies are eventually revealed to have security flaws, and it's inevitable that iOS 12 JavaScript Core will be too. A user who refuses to upgrade is not only risking their own data, but everyone else who might be subject to botnet or DDOS attacks from their compromised machine.

If we really care about users - if we care about security, if we want the web to be the best it can be - we cannot get into the business of polyfilling old browsers to act like new ones. That's what we did in the 2000s and it was a failure. It's unsustainable and it removes a powerful incentive for browser vendors to fix their rubbish software.

The real mitigation for issues like this is simple: build websites and services that work without JavaScript. Render HTML on the server wherever possible and make sure that truly essential JavaScript is isolated from exceptions raised by the nonessential stuff. Program defensively and you will create web applications that are not just resilient to client bugs but a whole host of other issues too.

You wouldn't build a bridge that could fail if a single bolt snapped, would you? So why build a service that lives or dies upon the correct behaviour of a single `array.reverse()`?

**Comment by hax** [comment]
> This is a serious issue in iOS 12 and will surely be fixed soon.

> it removes a powerful incentive for browser vendors to fix their halfbaked releases.

Do you notice that your first assertion and the last assertion are incompatible? 🤓

---

This project only provide a technical workaround for the bug. We never say everyone should use it. We never say Apple don't need to fix it. We never say users are ok to keep use the buggy version when Apple provide the updates. In fact, all such things are beyond the control of the author/contributors of this project, so do not attack a strawman.

In real world, many sites/apps can just ignore the bug and this project. But if someone meet the problems due to this bug, they need a solution. Especially, it's not a minor bug, but a really serious bug, which can corrupt the data on the page at all. In many cases, waiting Apple release updates and then waiting your users upgrade their OS/Safari may not be thought as a **acceptable solution**.

Even no problem yet, we can expect the largest platforms like Facebook or Wechat, and the sites/apps related to money like Amazon, Taobao, or even Bank/Finance/Exchange... may decide to land a workaround code to save the users and the business from the risk. Note, these are totally *business decisions*, not *technical decisions*, even we delete this repo won't change their decisions at all.

And every project have its life cycle. We hope this polyfill can be dropped soon (several weeks to months), but it not depends on we developers, because we can't decide when Apple land the updates and when people upgrade their iOS or Safari.

---

And some polyfill have to have much longer life cycle. For example, I have a iPhone 5 as my backup phone, and there may be many people still use old devices because not everyone can afford $749+. And iPhone 5 can not upgrade to iOS 12. So we don't worry such old device suffer this bug, but they may suffer other bugs, and you will never expect the vendors provide updates anymore. And blaming users not buying new device is very inappropriate. The only viable, moral, responsible solution we developers can afford is trying to provide some technique workaround even they are doomed.

---

About the script bloat and the dependencies problem, it's a common issue of all polyfills. Ideally, we should use server-side adaption like polyfill.io service. But for this case, the polyfill is very small and we expect it could be removed in months, so I think it's not a big deal. Anyway this is out of the scope of this project.

**Comment by zhangenming** [comment]
can we privide a function that called ios12NeedPolyfill  use by
`if (!ios12NeedPolyfill()){return}`

**Comment by hax** [comment]
@zhangenming 

The `buggy()` function in the source is just your `ios12NeedPolyfill`.

If you need on-demand load or server adaption by UA detection to save a request , see https://github.com/fanmingfei/array-reverse-ios12#ua-sniffing

Client sample code:
```html
...
<script>
if (/Version\/12\.0.*Safari\//.test(navigator.userAgent))
  loadScript('https://cdn.jsdelivr.net/npm/array-reverse-polyfill')
// Assume you have `loadScript()` available to create and insert the script tag.
</script>
...
```

Server-side adaption sample (in PHP):
```php
...
<? if (preg_match('#Version/12\.0.*Safari/#', $_SERVER['HTTP_USER_AGENT'])): ?>
<script src="https://cdn.jsdelivr.net/npm/array-reverse-polyfill"></script>
<? endif; ?>
...
```
